# Generated by Django 4.2.2 on 2023-09-24 16:29

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookClubs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('admin', models.IntegerField(default=0)),
                ('members', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), null=True, size=50)),
                ('botws', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('isbn', models.CharField(default='', max_length=20)),
                ('bname', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=20)),
                ('year', models.CharField(default='', max_length=4)),
                ('cid', models.IntegerField(default=0)),
                ('summary', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Covers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cfile', models.ImageField(default='def.jpg', null=True, upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField(default=0)),
                ('bcid', models.IntegerField(default=0)),
                ('content', models.CharField(max_length=50)),
                ('botw', models.IntegerField(default=0)),
                ('time', models.TimeField(default=datetime.time(21, 59, 42, 888394))),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('isbn', models.CharField(default='', max_length=20)),
                ('bname', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=20)),
                ('year', models.CharField(default='', max_length=4)),
                ('cover', models.CharField(null=True)),
                ('summary', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('otp', models.IntegerField(null=True)),
                ('exp', models.DateTimeField(null=True)),
                ('em', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pfile', models.ImageField(default='sunny.jpg', null=True, upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField(default=0)),
                ('bid', models.IntegerField(default=0)),
                ('rev', models.CharField(max_length=200)),
                ('stars', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('passw', models.CharField(max_length=10)),
                ('dob', models.DateField(default=datetime.date.today)),
                ('gen', models.CharField(max_length=1, null=True)),
                ('ans', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), null=True, size=5)),
                ('wl', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), null=True, size=None)),
                ('read', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), null=True, size=None)),
                ('pid', models.IntegerField(default=0)),
                ('recents', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), null=True, size=None)),
                ('bio', models.CharField(default='', max_length=20)),
                ('req', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), null=True, size=None)),
                ('friend', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), null=True, size=None)),
            ],
        ),
    ]
