# Generated by Django 4.2.2 on 2023-09-24 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='cover',
        ),
        migrations.AlterField(
            model_name='feed',
            name='time',
            field=models.TimeField(default=datetime.time(22, 1, 0, 35658)),
        ),
    ]
