# Generated by Django 4.2.2 on 2023-09-24 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0002_remove_library_cover_alter_feed_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Library',
        ),
        migrations.AlterField(
            model_name='feed',
            name='time',
            field=models.TimeField(default=datetime.time(22, 1, 58, 628175)),
        ),
    ]
