# Generated by Django 4.2.2 on 2023-09-24 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0006_alter_feed_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('isbn', models.CharField(default='', max_length=20)),
                ('bname', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=20)),
                ('year', models.CharField(default='', max_length=20)),
                ('cover', models.CharField(max_length=50)),
                ('summary', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='feed',
            name='time',
            field=models.TimeField(default=datetime.time(22, 5, 22, 273788)),
        ),
    ]
