# Generated by Django 4.2.2 on 2023-09-24 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0007_booklist_alter_feed_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklist',
            name='author',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='cover',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='feed',
            name='time',
            field=models.TimeField(default=datetime.time(22, 15, 52, 124618)),
        ),
    ]
