# Generated by Django 4.2.2 on 2023-09-24 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0008_alter_booklist_author_alter_booklist_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='time',
            field=models.TimeField(default=datetime.time(22, 16, 42, 78242)),
        ),
    ]
