# Generated by Django 4.2.2 on 2023-09-24 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0010_alter_booklist_summary_alter_feed_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklist',
            name='genre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='year',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='feed',
            name='time',
            field=models.TimeField(default=datetime.time(22, 17, 48, 191139)),
        ),
    ]
