# Generated by Django 4.2.2 on 2023-09-24 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0011_alter_booklist_genre_alter_booklist_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='time',
            field=models.TimeField(default=datetime.time(22, 35, 19, 671115)),
        ),
    ]
