# Generated by Django 4.2.2 on 2023-09-24 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0013_allbooks_alter_feed_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllBooks',
        ),
        migrations.DeleteModel(
            name='BookList',
        ),
        migrations.AlterField(
            model_name='feed',
            name='time',
            field=models.TimeField(default=datetime.time(23, 3, 9, 132222)),
        ),
    ]
