# Generated by Django 4.2.2 on 2023-09-25 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0016_alter_books_author_alter_books_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='replyto',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feed',
            name='time',
            field=models.TimeField(default=datetime.time(20, 15, 12, 162689)),
        ),
    ]
