# Generated by Django 4.2.2 on 2023-09-25 14:57

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0017_reviews_replyto_alter_feed_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='replyto',
        ),
        migrations.AddField(
            model_name='reviews',
            name='replies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='feed',
            name='time',
            field=models.TimeField(default=datetime.time(20, 27, 53, 456728)),
        ),
    ]
