# Generated by Django 4.2.2 on 2023-09-25 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0019_alter_feed_time_alter_reviews_replies'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='isreply',
            field=models.IntegerField(default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='feed',
            name='time',
            field=models.TimeField(default=datetime.time(20, 34, 45, 264339)),
        ),
    ]
