# Generated by Django 4.2.2 on 2023-10-07 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0022_remove_reviews_isreply_remove_reviews_replies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='reads',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feed',
            name='time',
            field=models.TimeField(default=datetime.time(19, 13, 29, 677388)),
        ),
    ]
