# Generated by Django 4.2.2 on 2023-10-08 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0023_books_reads_alter_feed_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repmonth', models.CharField(default='')),
                ('monthacc', models.IntegerField(default=0)),
                ('monthreads', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='feed',
            name='time',
            field=models.TimeField(default=datetime.time(16, 27, 38, 553465)),
        ),
    ]
