# Generated by Django 4.2.2 on 2023-10-08 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0024_reports_alter_feed_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='repyear',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='feed',
            name='time',
            field=models.TimeField(default=datetime.time(16, 29, 31, 107213)),
        ),
    ]
