# Generated by Django 4.2.2 on 2023-10-08 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0025_reports_repyear_alter_feed_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='time',
            field=models.TimeField(default=datetime.time(16, 31, 0, 725180)),
        ),
        migrations.AlterField(
            model_name='reports',
            name='repmonth',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reports',
            name='repyear',
            field=models.IntegerField(default=0),
        ),
    ]
